---
version: '3'
services:

# START SERVICE vcwc/dotnetcore/runtime
  dotnetcore:
    image: ${VCW_REGISTRY}mcr.microsoft.com/dotnetcore.runtime:3.1
    environment: [${VCW_STACK_DOTNETCORE_RUNTIME_ENVIRONMENT}]
    command: [${VCW_STACK_DOTNETCORE_RUNTIME_COMMAND}]
    volumes: ['${VCW_STACK_GLOBAL_STACKPREFIX}_dotnetcore_runtime_volume:/app']
    ports: []
    networks: [${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay]
    deploy:
      mode: ${VCW_STACK_DOTNETCORE_RUNTIME_DEPLOY_MODE}
      resources:
        limits:
          memory: '${VCW_STACK_DOTNETCORE_RUNTIME_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${VCW_STACK_DOTNETCORE_RUNTIME_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${VCW_STACK_DOTNETCORE_RUNTIME_COMPOSE_EXTENSIONS}
# END SERVICE vcwc/dotnetcore/runtime

networks: {${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay: { external: true }}
volumes: {${VCW_STACK_GLOBAL_STACKPREFIX}_dotnetcore_runtime_volume: { external: true }}
${VCW_STACK_GLOBAL_COMPOSE_EXTENSIONS}
